# Generated by Django 3.0.3 on 2023-11-12 03:13

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('I.P', 'Instructor de planta'), ('I.C', 'Instructor contratista'), ('M', 'Aprendiz'), ('ADM', 'Administrativo')], default='I.P', max_length=5)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('P.E', 'Permiso especial'), ('Pasaporte', 'Pasaporte'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad'), ('R.C', 'Registro civil')], default='C.C', max_length=11)),
                ('numero_documento', models.IntegerField(unique=True)),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('correo_soy_sena', models.EmailField(max_length=254, unique=True)),
                ('primer_telefono', models.IntegerField(unique=True)),
                ('segundo_telefono', models.IntegerField(blank=True, default='', null=True)),
                ('numero_ficha', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingres_sistema', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.CharField(max_length=80)),
                ('nombre_2', models.CharField(blank=True, max_length=80, null=True)),
                ('apellido_1', models.CharField(max_length=80)),
                ('apellido_2', models.CharField(blank=True, max_length=80, null=True)),
                ('id_tipo_documento', models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('P.E', 'Permiso especial'), ('Pasaporte', 'Pasaporte'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad'), ('R.C', 'Registro civil')], default='C.C', max_length=11)),
                ('numero_documento', models.CharField(max_length=80, unique=True)),
                ('correo_sena', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('correo_soy_sena', models.EmailField(max_length=254, unique=True)),
                ('celular_1', models.CharField(max_length=80, unique=True)),
                ('celular_2', models.CharField(blank=True, max_length=80, null=True)),
                ('id_rol', models.CharField(choices=[('I.P', 'Instructor de planta'), ('I.C', 'Instructor contratista'), ('M', 'Monitor')], default='I.C', max_length=5)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('id_area_instrtuctor', models.CharField(choices=[('Soft', 'Software')], default='Soft', max_length=6)),
                ('firma_electronica', models.ImageField(upload_to='')),
                ('estado_cuenta', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_user_permissions', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(choices=[('Consu', 'Consumible'), ('Devo', 'Devolutivo')], default='Devo', max_length=7)),
                ('nombre_material', models.CharField(max_length=40)),
                ('modelo_material', models.CharField(max_length=40)),
                ('ubicacion_material', models.CharField(choices=[('Bod', 'Bodega'), ('Z1', 'Zona 1'), ('Z2', 'Zona 2'), ('Z3', 'Zona 3'), ('Z4', 'Zona 4'), ('Z5', 'Zona 5'), ('Z6', 'Zona 6'), ('Admin', 'Administrativos'), ('N.A', 'No aplica'), ('Comp', 'Competencia')], default='Z1', max_length=7)),
                ('valor_material', models.IntegerField()),
                ('estado_material', models.CharField(choices=[('Dis', 'Disponible'), ('Pres', 'Préstamo'), ('Gara', 'Garantía'), ('Sop', 'Soporte'), ('DB', 'De baja'), ('Entr', 'Entregado')], default='Dis', max_length=6)),
                ('especificacion_tecnica_material', models.CharField(max_length=150)),
                ('codigo_barras_original_material', models.CharField(max_length=50, unique=True)),
                ('codigo_barras_sena_material', models.CharField(max_length=50, unique=True)),
                ('fecha_ingreso_material', models.DateField(auto_now_add=True)),
                ('actualizacion_material', models.DateField(auto_now_add=True)),
                ('encargado_registrar_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_ingresar_consumible_sistema', to='App_SistemaGestionInventario.CustomUser')),
                ('instructor_ecargado_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_material', to='App_SistemaGestionInventario.CustomUser')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='PrestamosDevolutivos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion_prestamo_material_devolutivo', models.CharField(choices=[('Bod', 'Bodega'), ('Z1', 'Zona 1'), ('Z2', 'Zona 2'), ('Z3', 'Zona 3'), ('Z4', 'Zona 4'), ('Z5', 'Zona 5'), ('Z6', 'Zona 6'), ('Admin', 'Administrativos'), ('N.A', 'No aplica'), ('Comp', 'Competencia')], default='Bod', max_length=5)),
                ('fecha_entrega_material_devolutivo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_material_devolutivo', models.DateField()),
                ('encargado_registra_material_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.CustomUser')),
                ('material_otorgado_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Materiales')),
                ('recibe_prestamo_material_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Clientes')),
            ],
            options={
                'verbose_name': 'Prestamo Devolutivo',
                'verbose_name_plural': 'Prestamos Devolutivos',
            },
        ),
        migrations.CreateModel(
            name='PrestamosConsumibles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion_prestamo_prestamo_consumible', models.CharField(choices=[('Bod', 'Bodega'), ('Z1', 'Zona 1'), ('Z2', 'Zona 2'), ('Z3', 'Zona 3'), ('Z4', 'Zona 4'), ('Z5', 'Zona 5'), ('Z6', 'Zona 6'), ('Admin', 'Administrativos'), ('N.A', 'No aplica'), ('Comp', 'Competencia')], default='N.A', max_length=5)),
                ('fecha_entrega_prestamo_consumible', models.DateField(auto_now_add=True)),
                ('encargado_registra_prestamo_consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.CustomUser')),
                ('material_otorgado_prestamo_consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Materiales')),
                ('recibe_prestamo_prestamo_consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Clientes')),
            ],
            options={
                'verbose_name': 'Prestamo consumible',
                'verbose_name_plural': 'Prestamos Consumibles',
            },
        ),
    ]
