# Generated by Django 3.0.3 on 2023-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permiso_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
