# Generated by Django 3.0.3 on 2023-12-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0002_customuser_permiso_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='segundo_telefono',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
