# Generated by Django 3.0.3 on 2023-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0003_auto_20231130_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo_soy_sena',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='primer_telefono',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundo_telefono',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
