# Generated by Django 3.0.3 on 2023-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0004_auto_20231130_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
