# Generated by Django 3.0.3 on 2023-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0006_prestamosdevolutivos_estado_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamosdevolutivos',
            name='estado_prestamo',
            field=models.BooleanField(default=True),
        ),
    ]
