# Generated by Django 3.0.3 on 2023-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0007_auto_20231203_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo_soy_sena',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
